### ISSUE TITLE
Needs to do error handling for the case of SSO Login fail.

### ISSUE THREAD

**Issue by kreeos** [sparcs-kaist/biseo_backend#8]
Right now, it just goes into Dashboard. If SSO login returns error, it has to do error handling
1. Failed log in will be treated by SSO
2. Therefore, error handling for the unknown errors have to be handled

**Comment by pacokwon** [comment]
#29 resolves this issue with SSO credentials check on `Client` instantiation

https://github.com/sparcs-kaist/biseo-backend/blob/0b6eae4a2318f6e65389624930a17ba9f46b8f21/src/utils/sso.ts#L3-L6
